[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

[rpc_endpoints]
allfeat-testnet = "https://harmonie-endpoint-02.allfeat.io/"
allfeat-local = "http://127.0.0.1:9944/"
